Extra items and power info
Zistack/Satisfactory-Optimizer pull request #8
Opened 2024-11-18 05:22 UTC by SpexGuy

This PR is the last two commits of #7, with the changes as requested to display only power_consumption instead of net_power_consumption when no power is generated.

2024-11-18 19:38 UTC, Zistack approved these changes

2024-11-18 19:44 UTC, Zistack requested changes
The README doesn't reflect the logic changes you made in the code.  Move the line about "This field is only present if the factory generates power" from "power_consumption" to "net_power_consumption".

2024-11-18 21:40 UTC, SpexGuy commented
Good catch! Readme updated.

2024-11-19 00:47 UTC, Zistack approved these changes

2024-11-19 00:50 UTC, merged